Asana 1199181647027082 : lors de la duplication d'une campagne on cop…
emilschn/yproject-crowdfunding-plugin pull request #106
Opened 2020-11-18 09:24 UTC by hmeneuvrier

…ie les infos quickbooks et le pourcentage common goods

2020-11-18 11:19 UTC, emilschn requested changes

2020-11-18 11:19 UTC, emilschn commented on includes/control/ajax.php
> +			$newcampaign->update_api();
ce serait mieux de mettre tout au-dessus du premier update_api pour n'en faire qu'un, non ?

2020-11-18 11:19 UTC, emilschn commented on includes/control/ajax.php
> +			$newcampaign->update_api();
ou de faire ça dans la fonction "duplicate" qui est déjà utilisée, pour regrouper la copie de données ?

2020-11-18 15:35 UTC, hmeneuvrier commented on includes/control/ajax.php
> +			$newcampaign->update_api();
oui j'ai mis au-dessus du premier update_api. dans duplicate ça me parait chelou..

2020-11-18 17:03 UTC, emilschn requested changes

2020-11-18 17:03 UTC, emilschn commented on includes/control/ajax.php
> +			// Copier automatiquement les informations pour la facturation lors de la duplication d'une levée
désolé, après réflexion, je pense que c'est vraiment mieux (comme dit dans mon autre commentaire) de le faire dans la fonction "duplicate" existante, qui s'occupe déjà de copier des données. Mieux vaut centraliser.
Et d'ailleurs la liaison des catégories pourrait être dedans aussi, je pense !

2020-11-19 08:16 UTC, hmeneuvrier commented on includes/control/ajax.php
> +			// Copier automatiquement les informations pour la facturation lors de la duplication d'une levée
ok ok ! :)

2020-11-19 08:38 UTC, hmeneuvrier commented on includes/control/ajax.php
> +			// Copier automatiquement les informations pour la facturation lors de la duplication d'une levée
Done !

2020-11-19 08:59 UTC, merged