Asana 1199691704128785 : affichage du total des royalties transférées
emilschn/yproject-crowdfunding-plugin pull request #149
Opened 2021-01-28 11:02 UTC by hmeneuvrier

2021-01-28 11:02 UTC, hmeneuvrier commented
Il y a aussi une correction d'une faute qui n'a rien à voir, et un pimpage de traces de les routes !

2021-01-28 16:27 UTC, emilschn requested changes

2021-01-28 16:27 UTC, emilschn commented on includes/control/ajax.php
> +					if($roi_item->status == 'transferred' ){
plutôt WDGROI::$status_transferred

2021-01-29 08:07 UTC, hmeneuvrier commented on includes/control/ajax.php
> +					if($roi_item->status == 'transferred' ){
done

2021-02-01 12:44 UTC, merged