Asana 1199183426050717 : Mes investissements - Préciser date du 1er v…
emilschn/yproject-crowdfunding-plugin pull request #186
Opened 2021-03-16 16:20 UTC by hmeneuvrier

…ersement

2021-03-17 09:58 UTC, emilschn requested changes

2021-03-17 09:58 UTC, emilschn commented on includes/control/ajax.php
> +						$investment_item[ 'status_str' ] = _e( 'account.investments.STARTED_CONTRACT', 'yproject' );
je suis surpris que ça marche, il faut remettre la fonction __ parce qu'elle retourne la chaine (tandis que _e fait un echo)

2021-03-17 09:58 UTC, emilschn commented on includes/control/ajax.php
> +						$investment_item[ 'status_str' ] = _e( 'account.investments.STARTED_CONTRACT', 'yproject' );
ça peut faire péter les retours du coup (je suis surpris que ça n'ait pas bloqué tes tests)

2021-03-18 09:01 UTC, hmeneuvrier commented on includes/control/ajax.php
> +						$investment_item[ 'status_str' ] = _e( 'account.investments.STARTED_CONTRACT', 'yproject' );
ok. j'ai fais des copier-coller sans faire gaffe

2021-03-22 09:51 UTC, merged