Asana 1195292288031677 : identifie les payments échoués dans le table…
emilschn/yproject-crowdfunding-plugin pull request #215
Opened 2021-05-20 15:10 UTC by hmeneuvrier

…au de contacts

2021-05-21 08:34 UTC, emilschn requested changes

2021-05-21 08:34 UTC, emilschn commented on includes/control/requests/ajax/project-dashboard.php
> +							$payment_status = __( "Paiement échoué", 'yproject' );
Ce n'est pas le bon cas : ici c'est le cas où le paiement est en attente et que la personne a été bloquée par le process d'authentification. C'est pour ça que c'est "Pas effectué".
Pour pouvoir afficher les échecs, il faudrait prendre les investissements qui sont en "failed".

2021-05-21 08:34 UTC, emilschn commented on includes/control/requests/ajax/project-dashboard.php
> +			$invest_amount = '<span class="payment-status-' . $post_invest_status_span_class . '">' .$item_invest['amount']. '</span>';
si tu fais ça, il affiche encore la pastille "error" ? Je crois qu'elle devrait toujours apparaitre ! (justement pour le cas ci-dessus)

2021-05-28 09:13 UTC, emilschn requested changes

2021-05-28 09:20 UTC, hmeneuvrier commented on includes/control/requests/ajax/project-dashboard.php
> +							// $post_invest_status_span_class = 'failed';
oups, c'est fait ! :)

2021-05-28 09:20 UTC, hmeneuvrier commented on includes/control/requests/ajax/project-dashboard.php
> +		// on retire l'investissement qui est "failed" si cet investisseur a des investissements plus récents "pending" ou "publish" dont le montant total est supérieur à l'investissement "failed"
gloups... j'essaie

2021-05-31 13:51 UTC, merged